# Generated by Django 4.0 on 2022-08-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='gene',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='query',
            name='var',
            field=models.CharField(default='', max_length=25),
        ),
    ]
