# Generated by Django 4.1 on 2022-08-08 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0002_alter_query_gene_alter_query_var'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='gene',
            field=models.CharField(choices=[('ABCD1', 'ABCD1'), ('ACADVL', 'ACADVL'), ('HBB', 'HBB')], max_length=25),
        ),
    ]
