# Generated by Django 4.1 on 2022-08-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0008_alter_query_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_added',
            field=models.DateField(editable=False),
        ),
    ]
