# Generated by Django 4.1 on 2022-08-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0009_alter_query_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date',
            field=models.CharField(default=20.22, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
