# Generated by Django 4.1 on 2022-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0010_query_date_alter_query_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='date',
        ),
        migrations.AddField(
            model_name='query',
            name='date_str',
            field=models.CharField(default='', editable=False, max_length=25),
            preserve_default=False,
        ),
    ]
