# Generated by Django 4.1 on 2022-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0012_alter_query_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
