# Generated by Django 4.1 on 2022-08-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0014_query_query_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
