# Generated by Django 4.1 on 2022-08-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0017_alter_query_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='id',
        ),
        migrations.AddField(
            model_name='query',
            name='query_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
