# Generated by Django 4.1 on 2022-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0018_remove_query_id_query_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
