# Generated by Django 4.1 on 2022-08-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0020_query_id_alter_query_query_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_id',
        ),
    ]
