# Generated by Django 4.1 on 2022-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0021_remove_query_query_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='date_added',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='user',
            new_name='user_created',
        ),
        migrations.AddField(
            model_name='query',
            name='user_updated',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
