# Generated by Django 4.1 on 2022-08-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('var_analysis', '0022_rename_date_added_query_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='user_created',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
