# Generated by Django 4.1 on 2022-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0024_remove_query_user_created_query_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='user',
            new_name='user_created',
        ),
        migrations.AlterField(
            model_name='query',
            name='user_updated',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
