# Generated by Django 4.1 on 2022-09-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0025_rename_user_query_user_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnomad', models.CharField(default='', max_length=1000)),
                ('dbsnp', models.CharField(default='', max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='var_analysis.query')),
            ],
        ),
    ]
