# Generated by Django 4.1 on 2022-09-23 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0026_variantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantinfo',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
