# Generated by Django 4.1 on 2022-09-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0027_variantinfo_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariantInfo',
            new_name='Evidence',
        ),
    ]
