# Generated by Django 4.1 on 2022-09-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0028_rename_variantinfo_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='cadd',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='clinvar',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='exac',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='polyphen2',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='provean',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='sift',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='splice_sites',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='ucsc',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
