# Generated by Django 4.1 on 2022-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0029_evidence_cadd_evidence_clinvar_evidence_exac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='active_sites',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='evidence',
            name='additional_info',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
