# Generated by Django 3.2.15 on 2022-10-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0031_auto_20221005_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='chrom',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='condition',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='hgvsp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='locus',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='rsid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='evidence',
            name='start_end',
            field=models.CharField(default='', max_length=50),
        ),
    ]
