# Generated by Django 3.2.15 on 2022-10-24 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0032_auto_20221007_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gnomad_evidence_category_1', models.CharField(default='', max_length=50)),
                ('gnomad_evidence_category_2', models.CharField(default='', max_length=50)),
                ('gnomad_evidence_category_3', models.CharField(default='', max_length=50)),
                ('gnomad_comment', models.CharField(default='', max_length=10000)),
                ('exac_evidence_category_1', models.CharField(default='', max_length=50)),
                ('exac_evidence_category_2', models.CharField(default='', max_length=50)),
                ('exac_evidence_category_3', models.CharField(default='', max_length=50)),
                ('exac_comment', models.CharField(default='', max_length=10000)),
                ('dbsnp_patho_1', models.CharField(default='', max_length=50)),
                ('dbsnp_patho_2', models.CharField(default='', max_length=50)),
                ('dbsnp_patho_3', models.CharField(default='', max_length=50)),
                ('dbsnp_comment', models.CharField(default='', max_length=10000)),
                ('clinvar_patho_1', models.CharField(default='', max_length=50)),
                ('clinvar_patho_2', models.CharField(default='', max_length=50)),
                ('clinvar_patho_3', models.CharField(default='', max_length=50)),
                ('clinvar_comment', models.CharField(default='', max_length=10000)),
                ('splice_evidence_category_1', models.CharField(default='', max_length=50)),
                ('splice_evidence_category_2', models.CharField(default='', max_length=50)),
                ('splice_evidence_category_3', models.CharField(default='', max_length=50)),
                ('splice_comment', models.CharField(default='', max_length=10000)),
                ('comp_evidence_category_1', models.CharField(default='', max_length=50)),
                ('comp_evidence_category_2', models.CharField(default='', max_length=50)),
                ('comp_evidence_category_3', models.CharField(default='', max_length=50)),
                ('comp_comment', models.CharField(default='', max_length=10000)),
                ('active_sites_evidence_category_1', models.CharField(default='', max_length=50)),
                ('active_sites_evidence_category_2', models.CharField(default='', max_length=50)),
                ('active_sites_evidence_category_3', models.CharField(default='', max_length=50)),
                ('active_sites_comment', models.CharField(default='', max_length=10000)),
                ('additional_evidence_category_1', models.CharField(default='', max_length=50)),
                ('additional_evidence_category_2', models.CharField(default='', max_length=50)),
                ('additional_evidence_category_3', models.CharField(default='', max_length=50)),
                ('additional_comment', models.CharField(default='', max_length=10000)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='var_analysis.evidence')),
            ],
        ),
    ]
