# Generated by Django 3.2.15 on 2022-10-27 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0034_auto_20221025_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='query',
            new_name='query_str',
        ),
        migrations.AddField(
            model_name='query',
            name='latest_evidence',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='var_analysis.evidence'),
        ),
    ]
