# Generated by Django 3.2.15 on 2022-11-01 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('var_analysis', '0035_auto_20221027_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='reviewer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_reviewer', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='First Reviewer'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_reviewer', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Second Reviewer'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_reviewer', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Third Reviewer'),
        ),
    ]
