# Generated by Django 3.2.15 on 2022-11-03 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('var_analysis', '0036_auto_20221101_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='active_sites_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='active_sites_evidence_category_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='active_sites_evidence_category_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='active_sites_evidence_category_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='additional_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='additional_evidence_category_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='additional_evidence_category_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='additional_evidence_category_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='clinvar_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='clinvar_patho_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='clinvar_patho_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='clinvar_patho_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='comp_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='comp_evidence_category_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='comp_evidence_category_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='comp_evidence_category_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp_patho_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp_patho_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp_patho_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='exac_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='exac_evidence_category_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='exac_evidence_category_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='exac_evidence_category_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad_evidence_category_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad_evidence_category_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad_evidence_category_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='reviewer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='First Reviewer'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Second Reviewer'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='reviewer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='Third Reviewer'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='splice_comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='splice_evidence_category_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='splice_evidence_category_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='splice_evidence_category_3',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
