# Generated by Django 3.2.15 on 2022-11-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0037_auto_20221103_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='rsid',
        ),
    ]
