# Generated by Django 3.2.15 on 2022-11-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0038_remove_evidence_rsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(default='', max_length=50)),
                ('condition', models.CharField(default='', max_length=50)),
                ('chrom', models.CharField(default='', max_length=50)),
                ('start_end', models.CharField(default='', max_length=100)),
                ('locus', models.CharField(default='', max_length=50)),
                ('transcript', models.CharField(default='', max_length=50)),
                ('np_id', models.CharField(default='', max_length=50)),
                ('gnomad_link', models.CharField(default='', max_length=50)),
                ('ncbi_gene_link', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_1_evidence',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_1_patho',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_2_evidence',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_2_patho',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_3_evidence',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='reviewer_3_patho',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
