# Generated by Django 3.2.15 on 2022-11-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0039_auto_20221107_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='id',
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
