# Generated by Django 3.2.15 on 2022-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0040_auto_20221107_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='gnomad_link',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='gene',
            name='ncbi_gene_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
