# Generated by Django 3.2.15 on 2022-11-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0041_auto_20221108_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='condition_site',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
