# Generated by Django 3.2.15 on 2022-11-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0043_alter_query_gene'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='running',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
