# Generated by Django 3.2.15 on 2022-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0044_query_running'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='running',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, null=True),
        ),
    ]
