# Generated by Django 3.2.15 on 2022-11-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0046_auto_20221110_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='date',
            new_name='date_ran',
        ),
    ]
