# Generated by Django 3.2.15 on 2022-11-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0047_rename_date_evidence_date_ran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='date_ran',
            field=models.CharField(editable=False, max_length=25),
        ),
    ]
