# Generated by Django 3.2.15 on 2022-12-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0049_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='active_sites',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
