# Generated by Django 3.2.15 on 2022-12-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0050_alter_evidence_active_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='active_sites_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='additional_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='additional_info',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='clinvar_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='comp_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='exac_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='splice_comment',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
    ]
