# Generated by Django 3.2.15 on 2022-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0051_auto_20221216_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='clinvar',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='dbsnp',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='exac',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='gnomad',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='splice_sites',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
