# Generated by Django 3.2.15 on 2023-01-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0052_auto_20221216_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_updated',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_str',
            field=models.CharField(blank=True, default='', editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='user_updated',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
