# Generated by Django 3.2.15 on 2023-01-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0053_auto_20230127_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='date_updated',
            field=models.CharField(editable=False, max_length=25),
        ),
        migrations.AlterField(
            model_name='query',
            name='query_str',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='query',
            name='user_updated',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
