# Generated by Django 3.2.15 on 2023-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0056_evidence_rsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='clinvar_date',
            field=models.CharField(default='xxx', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='clinvar_id',
            field=models.CharField(default='xxx', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='clinvar_interp',
            field=models.CharField(default='xxx', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
