# Generated by Django 3.2.15 on 2023-03-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0057_auto_20230323_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='clinvar_acc',
            field=models.CharField(default='xxx', editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
