# Generated by Django 3.2.15 on 2023-03-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0058_evidence_clinvar_acc'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='pubmed',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
