# Generated by Django 3.2.15 on 2023-04-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0059_evidence_pubmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='google',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
