# Generated by Django 3.2.15 on 2023-04-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0060_evidence_google'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='pubsearch',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
