# Generated by Django 3.2.15 on 2023-07-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('var_analysis', '0061_evidence_pubsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='norm_var',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
    ]
